language: rust
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true

jobs:
    include:
        - stage: "Notify"
          script: 
            - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
            - chmod +x send.sh
            - ./send.sh success $WEBHOOK_URL

cache: cargo
